version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

